import TreeStack

#print axioms TreeStack.universal_stackable_gt_card
#print axioms TreeStack.universal_stackable_succ
#print axioms TreeStack.F_sub_three_le
#print axioms TreeStack.F_eq_neg_odd_iff
#print axioms TreeStack.F_eq_nonneg_iff
#print axioms TreeStack.one_vertex_flux_le
#print axioms TreeStack.one_vertex_flux_mod_three
#print axioms TreeStack.rootEstimate_corrected_expansion
#print axioms TreeStack.card_add_one_le_rootEstimate
#print axioms TreeStack.card_add_one_le_estim
#print axioms TreeStack.OrientedBranch.parent_not_mem_vertices
#print axioms TreeStack.OrientedBranch.card_lt_total
#print axioms TreeStack.OrientedBranch.childBranch_vertices_subset
#print axioms TreeStack.OrientedBranch.childBranch_vertices_ssubset
#print axioms TreeStack.OrientedBranch.childBranch_card_lt
#print axioms TreeStack.OrientedBranch.edge_leaving_vertices_eq_boundary
#print axioms TreeStack.OrientedBranch.eq_root_of_mem_vertices_adj_parent
#print axioms TreeStack.OrientedBranch.branchMessage_eq_some_of_occupied
#print axioms TreeStack.OrientedBranch.branchMessage_eq_empty_iff
#print axioms TreeStack.OrientedBranch.branchMessage_ne_empty_of_occupied


#print axioms TreeStack.orderedTasks_safe
#print axioms TreeStack.OrientedBranch.branchMessage_congr_vertices
#print axioms TreeStack.OrientedBranch.childBranch_carrier_subset
#print axioms TreeStack.OrientedBranch.childBranch_vertices_disjoint
#print axioms TreeStack.OrientedBranch.BranchReach.eq_of_not_mem_carrier
#print axioms TreeStack.OrientedBranch.BranchReach.exists_moveSignature
#print axioms TreeStack.OrientedBranch.BranchReach.empty_boundary_nonincrease
#print axioms TreeStack.OrientedBranch.BranchReach.empty_boundary_mod_three
#print axioms TreeStack.OrientedBranch.ClearOutcome.exists_emptyExcursion_signature
#print axioms TreeStack.OrientedBranch.signature_branchFlux_bounds
#print axioms TreeStack.OrientedBranch.ClearOutcome.boundary_le_message
#print axioms TreeStack.OrientedBranch.ClearOutcome.no_positive_boundary_of_message_nonpos

#check TreeStack.MoveSignature
#check TreeStack.OrientedBranch.MoveSignature.boundaryFlux
#check TreeStack.OrientedBranch.MoveSignature.FeasibleClearing
#check TreeStack.OrientedBranch.MoveSignature.EmptyExcursion
#check TreeStack.OrientedBranch.BranchReach
#check TreeStack.OrientedBranch.ExactBoundaryInvariant
