import TreeStack

#print axioms TreeStack.universal_stackable_gt_card
#print axioms TreeStack.universal_stackable_succ
#print axioms TreeStack.F_sub_three_le
#print axioms TreeStack.F_eq_neg_odd_iff
#print axioms TreeStack.F_eq_nonneg_iff
#print axioms TreeStack.one_vertex_flux_le
#print axioms TreeStack.one_vertex_flux_mod_three
#print axioms TreeStack.rootEstimate_corrected_expansion
#print axioms TreeStack.card_add_one_le_rootEstimate
#print axioms TreeStack.card_add_one_le_estim
#print axioms TreeStack.OrientedBranch.parent_not_mem_vertices
#print axioms TreeStack.OrientedBranch.card_lt_total
#print axioms TreeStack.OrientedBranch.childBranch_vertices_subset
#print axioms TreeStack.OrientedBranch.childBranch_vertices_ssubset
#print axioms TreeStack.OrientedBranch.childBranch_card_lt
#print axioms TreeStack.OrientedBranch.edge_leaving_vertices_eq_boundary
#print axioms TreeStack.OrientedBranch.eq_root_of_mem_vertices_adj_parent
#print axioms TreeStack.OrientedBranch.branchMessage_eq_some_of_occupied
#print axioms TreeStack.OrientedBranch.branchMessage_eq_empty_iff
#print axioms TreeStack.OrientedBranch.branchMessage_ne_empty_of_occupied


#print axioms TreeStack.orderedTasks_safe
#print axioms TreeStack.OrientedBranch.branchMessage_congr_vertices
#print axioms TreeStack.OrientedBranch.childBranch_carrier_subset
#print axioms TreeStack.OrientedBranch.childBranch_vertices_disjoint
#print axioms TreeStack.OrientedBranch.BranchReach.eq_of_not_mem_carrier
#print axioms TreeStack.OrientedBranch.BranchReach.exists_moveSignature
#print axioms TreeStack.OrientedBranch.BranchReach.empty_boundary_nonincrease
#print axioms TreeStack.OrientedBranch.BranchReach.empty_boundary_mod_three
#print axioms TreeStack.OrientedBranch.ClearOutcome.exists_emptyExcursion_signature
#print axioms TreeStack.OrientedBranch.signature_branchFlux_bounds
#print axioms TreeStack.OrientedBranch.ClearOutcome.boundary_le_message
#print axioms TreeStack.OrientedBranch.ClearOutcome.no_positive_boundary_of_message_nonpos

#print axioms TreeStack.OrientedBranch.exists_childBranch_mem_of_mem_vertices_ne_root
#print axioms TreeStack.OrientedBranch.parent_not_mem_childBranch_carrier
#print axioms TreeStack.OrientedBranch.BranchReach.repeat_move
#print axioms TreeStack.OrientedBranch.taskGainSum_occupiedChildTasks
#print axioms TreeStack.OrientedBranch.executeOccupiedTaskSchedule
#print axioms TreeStack.OrientedBranch.executeAllOccupiedChildren
#print axioms TreeStack.OrientedBranch.attainRootTransfer_even
#print axioms TreeStack.OrientedBranch.attainRootTransfer_odd
#print axioms TreeStack.OrientedBranch.attainRootTransfer_ge_two
#print axioms TreeStack.OrientedBranch.boundary_attainment
#print axioms TreeStack.OrientedBranch.exactBoundaryInvariant

#check TreeStack.MoveSignature
#check TreeStack.OrientedBranch.MoveSignature.boundaryFlux
#check TreeStack.OrientedBranch.MoveSignature.FeasibleClearing
#check TreeStack.OrientedBranch.MoveSignature.EmptyExcursion
#check TreeStack.OrientedBranch.BranchReach
#check TreeStack.OrientedBranch.ExactBoundaryInvariant
#check TreeStack.OrientedBranch.boundary_attainment
#check TreeStack.OrientedBranch.exactBoundaryInvariant

#print axioms TreeStack.incidentBranch_vertices_disjoint
#print axioms TreeStack.exists_incidentBranch_mem_of_ne_root
#print axioms TreeStack.taskGainSum_rootTasks
#print axioms TreeStack.Reach.exists_moveSignature
#print axioms TreeStack.executeRootTaskSchedule
#print axioms TreeStack.executeAllRootTasks
#print axioms TreeStack.stackableAt_of_score_pos
#print axioms TreeStack.score_pos_of_stackableAt
#print axioms TreeStack.stackableAt_iff_score_pos
#print axioms TreeStack.not_stackable_iff_all_scores_nonpos

#check TreeStack.score
#check TreeStack.stackableAt_iff_score_pos
#check TreeStack.not_stackable_iff_all_scores_nonpos

#print axioms TreeStack.obstruction
#print axioms TreeStack.mass_obstruction
#print axioms TreeStack.OrientedBranch.obstructionHeight
#print axioms TreeStack.OrientedBranch.obstructionHeight_eq_one_add_two_mul_internalPotential
#print axioms TreeStack.OrientedBranch.obstruction_branchMessage
#print axioms TreeStack.OrientedBranch.obstruction_score_root_of_parent_score_zero
#print axioms TreeStack.obstruction_score_selected_root
#print axioms TreeStack.OrientedBranch.obstruction_scores_zero_on_vertices
#print axioms TreeStack.obstruction_score_eq_zero
#print axioms TreeStack.obstruction_not_stackable
#print axioms TreeStack.exists_rootEstimate_eq_estim
#print axioms TreeStack.exists_nonstackable_mass_estim_sub_one

#check TreeStack.obstruction
#check TreeStack.OrientedBranch.obstructionHeight
#check TreeStack.obstruction_score_eq_zero
#check TreeStack.obstruction_not_stackable
#check TreeStack.exists_nonstackable_mass_estim_sub_one


#print axioms TreeStack.defect_left_nonneg
#print axioms TreeStack.defect_right_nonneg
#print axioms TreeStack.defect_not_both_nonneg
#print axioms TreeStack.defect_two_negative
#print axioms TreeStack.defect_edge_classification
#print axioms TreeStack.defect_left_budget
#print axioms TreeStack.defect_right_budget

#check TreeStack.defect_edge_classification

#print axioms TreeStack.scoreDefect
#print axioms TreeStack.defectEdgeState_of_equations
#print axioms TreeStack.OrientedBranch.defect_equations_of_both_occupied
#print axioms TreeStack.OrientedBranch.defectEdgeState_of_scores_nonpos

#check TreeStack.OrientedBranch.defectEdgeState_of_scores_nonpos


#print axioms TreeStack.OrientedBranch.vertices_disjoint_reverseBranch
#print axioms TreeStack.OrientedBranch.mem_vertices_or_mem_reverseBranch
#print axioms TreeStack.OrientedBranch.vertices_union_reverseBranch
#print axioms TreeStack.OrientedBranch.occupied_or_reverse_occupied
#print axioms TreeStack.OrientedBranch.score_eq_effectiveInput_of_reverse_not_occupied
#print axioms TreeStack.OrientedBranch.defectEdgeState_of_supportEdge
#print axioms TreeStack.score_eq_of_support_subset_singleton
#print axioms TreeStack.exists_other_occupied_of_all_scores_nonpos

#check TreeStack.OrientedBranch.SupportEdge
#check TreeStack.OrientedBranch.defectEdgeState_of_supportEdge
#check TreeStack.exists_other_occupied_of_all_scores_nonpos

#print axioms TreeStack.OrientedBranch.root_pos_of_supportEdge_of_no_child_supportEdge

-- Retained support-core path closure and forced defect orientations (PR #15)
#print axioms TreeStack.OrientedBranch.reverse_child_occupied_of_supportEdge
#print axioms TreeStack.OrientedBranch.child_supportEdge_iff_occupied_of_supportEdge
#check TreeStack.OrientedBranch.SupportDescent
#print axioms TreeStack.OrientedBranch.supportDescent_of_mem_pos
#print axioms TreeStack.OrientedBranch.exists_child_supportEdge_of_supportEdge_of_root_not_pos
#check TreeStack.OrientedBranch.DefectArrow
#print axioms TreeStack.OrientedBranch.reverse_message_neg_of_defectArrow
#print axioms TreeStack.OrientedBranch.not_defectArrow_reverse
#print axioms TreeStack.OrientedBranch.defectArrow_tail_budget
#print axioms TreeStack.OrientedBranch.supportEdge_defectArrow_or_reverse_or_both_neg

-- Ambient-root incident-owner assignment for arbitrary tree-edge subsets
#check TreeStack.OrientedBranch.rootedOwner
#check TreeStack.OrientedBranch.rootedOther
#print axioms TreeStack.OrientedBranch.rootedOther_adj_rootedOwner
#print axioms TreeStack.OrientedBranch.rootedOwner_dist_eq_rootedOther_add_one
#print axioms TreeStack.OrientedBranch.rootedOwner_other_edge
#print axioms TreeStack.OrientedBranch.eq_of_adj_owner_of_dist
#print axioms TreeStack.OrientedBranch.edge_eq_of_rootedOwner_eq
#print axioms TreeStack.OrientedBranch.rootedOwner_reverse

-- Defective retained-edge forest and weighted charging algebra
#check TreeStack.OrientedBranch.DefectiveSupportEdge
#print axioms TreeStack.OrientedBranch.defectiveSupportEdge_reverse_iff
#check TreeStack.OrientedBranch.defectiveGraph
#print axioms TreeStack.OrientedBranch.defectiveGraph_le_tree
#print axioms TreeStack.OrientedBranch.defectiveGraph_isAcyclic

#print axioms TreeStack.oriented_edge_excess_bound
#print axioms TreeStack.oriented_excess_le_tail_budget
#print axioms TreeStack.oriented_excess_le_head_budget
#print axioms TreeStack.two_negative_edge_excess_eq
#print axioms TreeStack.two_negative_excess_le_owner_budget

